(ski | desk) <number_small>: user.desktop(number_small)
(ski | desk) right: user.desktop(2)
(ski | desk) next: user.desktop_next()
(ski | desk) left: user.desktop(1)
desk last: user.desktop_last()
desk show: user.desktop_show()
window move desk <number>: user.window_move_desktop(number)
window move desk left: user.window_move_desktop_left()
window move desk right: user.window_move_desktop_right()
